# Generated by Django 4.0 on 2021-12-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YelloTaxiTrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('VendorID', models.BigIntegerField(blank=True, null=True)),
                ('tpep_pickup_datetime', models.DateTimeField(blank=True, null=True)),
                ('tpep_dropoff_datetime', models.DateTimeField(blank=True, null=True)),
                ('passenger_count', models.IntegerField(blank=True, null=True)),
                ('trip_distance', models.FloatField(blank=True, null=True)),
                ('RatecodeID', models.IntegerField(blank=True, null=True)),
                ('store_and_fwd_flag', models.CharField(blank=True, max_length=255, null=True)),
                ('PULocationID', models.IntegerField(blank=True, null=True)),
                ('DOLocationID', models.IntegerField(blank=True, null=True)),
                ('payment_type', models.IntegerField(blank=True, null=True)),
                ('fare_amount', models.FloatField(blank=True, null=True)),
                ('extra', models.FloatField(blank=True, null=True)),
                ('mta_tax', models.FloatField(blank=True, null=True)),
                ('tip_amount', models.FloatField(blank=True, null=True)),
                ('tolls_amount', models.FloatField(blank=True, null=True)),
                ('improvement_surcharge', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('congestion_surcharge', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
